### ISSUE TITLE
broken link Apple Sign in tutorial

### ISSUE THREAD

**Issue by danilomna** [bizz84/code-with-andrea-issue-tracker#2]
Hi Andrea, 

your tutoriais are awesome. Now Im trying to learn Apple Sign in, but couldnt get code example due to broken link, could you please fix it? Error 404

this is he tutotial page (ok)
https://codewithandrea.com/videos/2020-01-20-apple-sign-in-flutter-firebase/

his is the broken link:
https://github.com/bizz84/apple_sign_in_firebase_flutter

**Comment by bizz84** [comment]
@danilomna apologies for the late reply. I fixed this now, the link should work.
