### ISSUE TITLE
Broken link when coming from Youtube for images

### ISSUE THREAD

**Issue by mikcatta** [bizz84/code-with-andrea-issue-tracker#3]
Broken link on https://www.youtube.com/watch?v=bdam6VY0Db0

It says "Note: To follow along from lesson 29 onwards, download this file and add it to the root of your project:
https://codewithandrea.com/videos/202..." but the file doesn't seem to exist.

**Comment by bizz84** [comment]
@mikcatta Thanks for reporting this! I have fixed the link in the YouTube description
